# Generated by Django 3.2.23 on 2023-12-18 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('post_picture', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_filter', models.CharField(choices=[('normal', 'Normal'), ('black_and_white', 'Black and White'), ('sepia', 'Sepia'), ('vintage', 'Vintage'), ('grayscale', 'Grayscale'), ('warm', 'Warm Tone'), ('cool', 'Cool Tone'), ('invert', 'Invert Colors'), ('blur', 'Blur'), ('sharpen', 'Sharpen')], default='normal', max_length=32, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
