# Generated by Django 3.2.23 on 2024-01-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
